logger_importUI <- function(id){
  ns <- NS(id)
  tagList(
  column(12,column(6,
                   h1("Import logger exports"),
                   HTML("<p>Use this page to import exports from dipwell data loggers (e.g. generated by WinSitu). Each import must be from the same logger installation.</p>")
  )),
  column(7,
         column(12,
                h3("Data to import"),
                HTML("<p>First, choose a .csv file to import using the template available <a href='log-export-template.csv'>here</a>. The date-time column must be formated as yyyy-mm-dd hh:mm, e.g. '2023-04-14 00:00'.</p>"),
                fileInput(ns("choose_csv"),label="Choose .csv file to import:", 
                          buttonLabel = "Browse...",
                          placeholder = "No file selected",
                          accept = c(
                            "text/csv",
                            "text/comma-separated-values,text/plain",
                            ".csv")
                          ),
                conditionalPanel(condition = "output.fileUploaded == 1",ns = ns,
                column(6,selectizeInput(ns("choose_site"), 
                                        label = "Choose site", 
                                        multiple = FALSE,
                                        choices = c(""),
                                        options = list(
                                          placeholder = 'Choose a site',
                                          onInitialize = I('function() { this.setValue(""); }')
                                        )
                                        )
                       ),
                column(6,
                       conditionalPanel(condition = "input.choose_site > 0",ns = ns,
                          selectizeInput(ns("choose_logger_install"), 
                                        label = "Choose a logger install",
                                        multiple = FALSE,
                                        choices = c(""),
                                        options = list(
                                          placeholder = 'Please select an option below',
                                          onInitialize = I('function() { this.setValue(""); }')
                                          )
                                        )
                       )
                       )
                )
         ),
         conditionalPanel(condition = "input.choose_logger_install >0 && output.fileUploaded == 1",ns = ns,
           column(12,
                h3("Log export information"),
                column(4,
                       airDatepickerInput(ns("log_date_time"),
                                          label = "Log export date / time:",
                                          timepicker = TRUE,
                                          dateFormat = "yyyy-MM-dd"),
                       textInput(ns("log_by"), 
                                 label = "Log export creator:", 
                                 placeholder = "Name of person who generated the log export"
                       )
                       ),
                column(4,
                       numericInput(ns("log_battery"),
                                    label = "Logger battery at export:",
                                    min = 0, max = 100, step = 1, value = 0
                       ),
                       numericInput(ns("log_memory"),
                                    label = "Logger memory at export:",
                                    min = 0, max = 100, step = 1, value = 0)
                       ),
                column(4,
                       timeInput(ns("log_logger_time"),
                                 label = "Logger time at export:",
                                 seconds = FALSE),
                       timeInput(ns("log_local_time"),
                                 label = "Local time at export:",
                                 seconds = FALSE)
                       )
                ),
           column(12,
                  column(12,
                         textAreaInput(ns("log_notes"), 
                                       label="Log export / import notes", 
                                       placeholder= "Add any relevant notes",
                                       resize = "vertical"
                         ),
                         actionButton(ns("import"),label = "Import log export"))
           )
         )
  ),
  column(5,
                h3("Data preview"),
                tabBox(width = 12,
                  tabPanel("Table",
                           conditionalPanel(condition = "output.fileUploaded == 0",ns = ns,
                                            p("No data to show")
                           ),
                           conditionalPanel(condition = "output.fileUploaded == 1",ns = ns,
                                            withSpinner(DT::dataTableOutput(ns("logger_data_table")))
                           )
                  )
                  ,
                  tabPanel("Plot",
                           conditionalPanel(condition = "output.fileUploaded == 0",ns = ns,
                                            p("No data to show")
                           ),
                           conditionalPanel(condition = "output.fileUploaded == 1",ns = ns,
                                            withSpinner(plotOutput(ns("logger_data_plot")))   
                           )

                    )
                )
         )
)}

logger_importServer <- function(id, con) {
  moduleServer(
    id,
    function(input, output, session) {
  
  #Reactive values for data to import
  data <- reactiveValues(import = NA, logger_installs = NA)
  
  #Upload csv and validate ----
  
  nms <- c("date_time","seconds","temperature","pressure") #Valid column names
  
  uploadData <- reactive({
    req(input$choose_csv)
    shiny::validate(need(tools::file_ext(input$choose_csv$datapath) == "csv","Invalid file type"))
    try(read.csv(input$choose_csv$datapath, header = TRUE))
  })
  
  observeEvent(uploadData(), {
    if(is.data.frame(uploadData()) && all(nms %in% names(uploadData())) && all(vapply(uploadData()[nms[2:4]],is.numeric,NA))){
      data$import <- uploadData()
      hideFeedback("choose_csv")
      data$import$date_time <- as.POSIXct(data$import$date_time,format = "%Y-%m-%d %H:%M", tz="GMT")
      
      output$logger_data_table <- DT::renderDataTable(
        datatable(data$import,
                  options = list(
                    bFilter = 0,
                    bLengthChange = 0
                    ),
                  colnames = c("Date / time", "Seconds", "Temperature", "Pressure (cm)"),
                  rownames = FALSE
                  )
        )
      
      d <- data$import
      rt <- max(d$temperature) - min(d$temperature)
      rp <- max(d$pressure) - min(d$pressure)
      
      rt0 <- 0.5*(max(d$temperature) + min(d$temperature))
      rp0 <- 0.5*(max(d$pressure) + min(d$pressure))
      
      f <- function(x){
        y <- (rp*(x-rt0)/rt) + rp0
        return(y)
      }
      
      g <- function(y){
        x <- rt*(y-rp0)/rp + rt0
        return(x)
      }
 
      output$logger_data_plot <- renderPlot(
        ggplot(data = d) + geom_line(aes(x = date_time, y = pressure, color = "Pressure")) +
          scale_y_continuous(name = 'Pressure (cm)',sec.axis = sec_axis(~ g(.), name = 'Temperature (°C)'))+
          geom_line(aes(x = date_time , y = f(temperature) , color = "Temperature")) + 
          theme(legend.position="top", legend.title = element_blank()) +
          xlab("Date")
        )
      
      } 
    else{
      showFeedback("choose_csv", "Invalid upload")
    }
  })
  


  output$fileUploaded <- reactive({
    return(isTruthy(uploadData()))
  })
  
  outputOptions(output, 'fileUploaded', suspendWhenHidden = FALSE)
  
  #SelectizeInput controls ----
  
  observe({

    log_insts <- dbGetQuery(con, "SELECT C.id AS site_id, C.site, A.id AS logger_install_id, A.logger, D.name AS config_name, B.install_name
                       FROM hydro_monitoring.logger_installs A, 
                       spatial.monitoring_hydro_installs B, 
                       spatial.fen_sites C, 
                       (SELECT DISTINCT ON (logger) id, logger, name, create_date FROM hydro_monitoring.logger_configs 
ORDER BY logger, create_date DESC) D
                       WHERE A.install = B.id 
                       AND A.logger = D.logger 
                       AND B.site = C.id 
                       AND A.remove_date IS NULL")
    
    data$logger_installs <- log_insts
    
    sites <- unique(log_insts[,c("site_id","site")])

    #update selectize with logger installs  
    sites_choices <- sites$site_id
    names(sites_choices) <- sites$site
    updateSelectizeInput(session, inputId = "choose_site", choices = sites_choices)
    
  })
  
  observeEvent(input$choose_site,{
    req(input$choose_site)
    log_insts <- data$logger_installs
    c <- log_insts[log_insts$site_id == input$choose_site,]
    logger_installs_choices <- c$logger_install_id
    names(logger_installs_choices) <- paste0("Logger ", c$logger," - Installation '", c$install_name, "'")
    updateSelectizeInput(session, inputId = "choose_logger_install", choices = logger_installs_choices)
    })
  
  
  
  #Modal for import progress----
  import_progress_modal <- function() {
    ns <- session$ns
    modalDialog(
      div("Import in progress",style="width:100%; text-align:center")
      , footer=NULL,size="s",easyClose=FALSE,fade=TRUE)
  }
  #Modal for import success----
  import_success_modal <- function() {
    ns <- session$ns
    modalDialog(
      div("Data successfully imported",style="width:100%; text-align:center")
      , footer=NULL,size="s",easyClose=TRUE,fade=TRUE)
  }
  #Modal for import error----
  import_error_modal <- function() {
    ns <- session$ns
    modalDialog(
      div("Import error",style="width:100%; text-align:center")
      , footer=NULL,size="s",easyClose=TRUE,fade=TRUE)
  }
  
  #Import----
  observeEvent(input$import,{
    
    if(isTruthy(input$log_date_time)){
      hideFeedback("log_date_time")
    }
    else{
      showFeedbackDanger("log_date_time","This field is required")
    }
    
    if(isTruthy(input$log_by)){
      hideFeedback("log_by")
    }
    else{
      showFeedbackDanger("log_by","This field is required")
    }
    
    
    if(isTruthy(input$log_battery)){
      hideFeedback("log_battery")
    }
    else{
      showFeedbackDanger("log_battery","This field is required")
    }
    
    
    if(isTruthy(input$log_memory)){
      hideFeedback("log_memory")
    }
    else{
      showFeedbackDanger("log_memory","This field is required")
    }
    req(input$choose_csv)
    req(input$choose_logger_install)
    req(input$log_by)
    req(input$log_battery)
    req(input$log_date_time)
    req(input$log_memory)
    
    if(isTruthy(data$import)){
      
      showModal(import_progress_modal())
      
            query <- paste("INSERT INTO hydro_monitoring.logger_imports (log_date_time,log_by,log_battery,log_memory,log_logger_time,log_local_time,logger_install,log_notes) VALUES (",
                     "'", input$log_date_time, "',",
                     "'", input$log_by, "',",
                     input$log_battery, ",",
                     input$log_memory, ",'",
                     input$log_logger_time, "','",
                     input$log_local_time,"',",
                     input$choose_logger_install,",'",
                     input$log_notes,
                     "') RETURNING id", sep="")
            import <- dbGetQuery(con, query)
            
            if(!is.na(import$id)){
              i <- data$import
              i$logger_import <- import$id
              insert <- pgInsert(
                conn = con,
                name = c(schema = "hydro_monitoring", table = "logger_data"),
                data.obj = i,
                partial.match = TRUE,
                upsert.using = c("date_time", "logger_import")
                )
              if(insert == TRUE){
                removeModal()
                showModal(import_success_modal())
                }
              
              else{
                #Delete the import info record if the import fails
                dbGetQuery(con,paste("DELETE FROM hydro_monitoring.logger_imports WHERE id = ",import$id,sep=""))
                removeModal()
                showModal(import_error_modal())
                }            
              }
    }
  })
})}

